title: Shaozhe Hao
logo: /assets/img/logo.png
description: Undergraduate in HUST
interest: ML & CV
location: Wuhan, China
email: szhao@hust.edu.cn
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
